version: "3.9"

services:
  devopsdb:
    image: brkdockerhub/myapp:database
    ports:
      - "3306:3306"
    deploy:
      replicas: 2 
    networks:
      - mynetwork

  application:
    image: brkdockerhub/myapp:application
    ports:
      - "2222:8080"
    deploy:
      replicas: 2  
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
